### ISSUE TITLE
whisper self

### ISSUE THREAD

**Issue by rafalohaki** [AlexProgrammerDE/PistonChat#67]
while whispering to mnyself i got warn
version latest commit build
[22:19:38 WARN]: java.io.IOException: No such file or directory
[22:19:38 WARN]: 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
[22:19:38 WARN]: 	at java.base/java.io.File.createNewFile(File.java:1043)
[22:19:38 WARN]: 	at PistonChat-1.5.3.jar//net.pistonmaster.pistonchat.utils.ConfigTool$PlayerDataManager.generateFile(ConfigTool.java:115)
[22:19:38 WARN]: 	at PistonChat-1.5.3.jar//net.pistonmaster.pistonchat.utils.ConfigTool$PlayerDataManager.loadData(ConfigTool.java:94)
[22:19:38 WARN]: 	at PistonChat-1.5.3.jar//net.pistonmaster.pistonchat.utils.ConfigTool$PlayerDataManager.<init>(ConfigTool.java:90)
[22:19:38 WARN]: 	at PistonChat-1.5.3.jar//net.pistonmaster.pistonchat.utils.ConfigTool.isHardIgnored(ConfigTool.java:56)
[22:19:38 WARN]: 	at PistonChat-1.5.3.jar//net.pistonmaster.pistonchat.utils.IgnoreTool.isIgnored(IgnoreTool.java:22)
[22:19:38 WARN]: 	at PistonChat-1.5.3.jar//net.pistonmaster.pistonchat.commands.whisper.WhisperCommand.onCommand(WhisperCommand.java:27)
[22:19:38 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[22:19:38 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
[22:19:38 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:942)
[22:19:38 WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64)
[22:19:38 WARN]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264)
[22:19:38 WARN]: 	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:311)
[22:19:38 WARN]: 	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:295)
[22:19:38 WARN]: 	at net.minecraft.server.network.PlayerConnection.b(PlayerConnection.java:2385)
[22:19:38 WARN]: 	at net.minecraft.server.network.PlayerConnection.lambda$handleChatCommand$21(PlayerConnection.java:2339)
[22:19:38 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.b(IAsyncTaskHandler.java:59)
[22:19:38 WARN]: 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
[22:19:38 WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[22:19:38 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[22:19:38 WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1388)
[22:19:38 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[22:19:38 WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185)
[22:19:38 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[22:19:38 WARN]: 	at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1365)
[22:19:38 WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1358)
[22:19:38 WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[22:19:38 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1336)
[22:19:38 WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1224)
[22:19:38 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[22:19:38 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by AlexProgrammerDE** [comment]
PistonChat no longer uses file system storage
